### PR TITLE
support sending NOTICEs

### PR DESCRIPTION
**Pull request by filippog**
hi,
thanks for pyaib! I'd like to be able to send NOTICE from the bot too, this PR addresses that by sharing the wrapping code with PRIVMSG, what do you think?

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by filippog** [comment]
CLA signed

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by fried** [comment]
Thanks, i'll merge this in.

**Comment by zodman** [comment]
awesome!!!!

**Pull request merged**
